apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aws9-portal
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: www.aws9.pri
    http:
      paths:
      - path: "/green(/|$)" #www.aws9.pri/shop
        pathType: Prefix
        backend:
          service:
            name: aws9-svc-green1
            port:
              number: 8081
      - path: "/blue(/|$)"
        pathType: Prefix
        backend:
          service:
            name: aws9-svc-blue1
            port:
              number: 8081