---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blue-pvc1
spec:
  storageClassName: nginx-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: green-pvc1
spec:
  storageClassName: nginx-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    