apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws9-deploy-default
spec:
  replicas: 3
  selector:
    matchLabels:
      color: default
  template:
    metadata:
      labels:
        color: default
    spec:
      containers:
        - name: aws9ctn-blue
          image: 211.183.3.100/nginx/aws9:blue
          resources:
            requests:
              cpu: "250m"  # CPU 요청 추가
              memory: "128Mi"  # 메모리 요청 추가
          volumeMounts:
          - name: default-data
            mountPath: /usr/share/nginx/html
      volumes:
        - name: default-data
          persistentVolumeClaim:
            claimName: default-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc-default
spec:
  ports:
  - name: aws9-port-default
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    color: default

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aws9-hpa
spec:
  maxReplicas: 10
  minReplicas : 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aws9-deploy-default
  targetCPUUtilizationPercentage: 60

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: keda-service-clusterIP1
#   namespace: default
# spec:
#   selector:
#     color: default
#   ports:
#   - name: keda-service-port
#     protocol: TCP
#     port: 8080
#     targetPort: 80
